spring:
    mail:
        host: smtp.qq.com
        username: 1379960679@qq.com
        password: uungoqqnvlqcjecf
        default-encoding: UTF-8
        port: 465
        protocol: stmp
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            one: #数据源1
                url: jdbc:mysql://localhost:3306/fly?serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
                driver-class-name: com.mysql.cj.jdbc.Driver
                username: xla
                password: xula19941129L.
                initial-size: 10
                max-active: 100
                min-idle: 10
                max-wait: 60000
                pool-prepared-statements: true
                max-pool-prepared-statement-per-connection-size: 20
                time-between-eviction-runs-millis: 60000
                min-evictable-idle-time-millis: 300000
                validation-query: SELECT 1 FROM DUAL
                test-while-idle: true
                test-on-borrow: false
                test-on-return: false
            two: #数据源2
                url: jdbc:mysql://localhost:3306/hblog?serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
                driver-class-name: com.mysql.cj.jdbc.Driver
                username: root
                password: 123456
                initial-size: 10
                max-active: 100
                min-idle: 10
                max-wait: 60000
                pool-prepared-statements: true
                max-pool-prepared-statement-per-connection-size: 20
                time-between-eviction-runs-millis: 60000
                min-evictable-idle-time-millis: 300000
                validation-query: SELECT 1 FROM DUAL
                test-while-idle: true
                test-on-borrow: false
                test-on-return: false


# mache

memcached:
    ip: 127.0.0.1
    port: 11211
is:
  dev: false
online:
    domain: http://127.0.0.1:8080=8

# mybatis
mybatis:
    type-aliases-package: com.xula.entity
